### ISSUE TITLE
TODO: Authentication

### ISSUE THREAD

**Issue by nghiaht** [nguyenminhdoan/Training-Nestjs#1]
Hi @nguyenminhdoan,
It would be great if you can write a Wiki in this repo about your "Authentication" solution.
A sample format is provided below, feel free to express about your solution.

# Authentication
## How to integrate frontend with backend?
(flow, which api, token response, request header..)
...
## How to authenticate user in your Nest.js controller?
(request header, which guard...)
...

**Comment by nguyenminhdoan** [comment]
hi @nghiaht,
**How to integrate frontend with backend?**
I'm gonna make a folder call API, in this folder, I will use Axios to call API and return a result, which will be used in context API "a statement management".
After call login API from BE, it should return for me
+ user information (_id, email, and hashed password)
+ bearer token which contains email information 
So in the FE, I will create a state called "isAuth", if I get the result after call API login, "isAuth" state will be true and I will display the dashboard layout based on state of "isAuth".

 **How to authenticate user in your Nest.js controller?**
I have created register and login router
+ register router: It will require "email" and "password", and when user types those fields, it will create a data in database include (email, hashed password, token). I use "Bcrypt" to hash password
+ login router: it also require "email" and "password", when user types those fields, I will compare to the password from user with the hashed password in DB. if password and email match, I will return user profile (email , id, hashed password and token)

So for other private routes, I will use JWT to allow or not allow user uses the private routes, by passing JWT in request header

**Comment by nghiaht** [comment]
That's great. But I suggest you to write the documentation (your last reply) shorter, focus on: Input -> Output, you can think about how you write shortest to help another people read and learn and use your implementation as fast as possible.
The authentication problem is common and important one in the app. You should develop your backend best before moving on frontend.

My example below
## How to integrate frontend with backend?
- Request to login and get the token
```
POST /api/login 
Request
{
  email
  password
}

Response
{
   token
}
```

- Later authenticated requests, attach the token in the requests's header and perform requests
```
const {token} = isAuth();
const {data} = service.requestA({token})
```

## How to authenticate user in your Nest.js controller?
Your answer above + How to get authenticated user context in Nest.js controllers?

Sum up: Write down minimal steps for others to **use** your solution, no need to describe how you implement them

**Comment by nguyenminhdoan** [comment]
**How to integrate frontend with backend?**
+ Request to login and get the token

**POST/auth/login**

Request
{
  email
  password
}
Response
{  
  user: {
    id,
    email,
    password
}
   token
}

**POST/auth/register**
Request
{
  email
  password
}
Response
{  
  user: {
    id,
    email,
    password
}

}

**How to authenticate user in your Nest.js controller?**
+ POST/auth/login

Body Request
{
  email
  password
}

use Bcrypt compare
{
   Body Request.password === user.password in database
}
if(true) {
return  
user: {
    id,
    email,
    password
}
else {
return HttpException('Invalid login', HttpStatus.UNAUTHORIZED)
}
}

**Comment by nghiaht** [comment]
Great, @nguyenminhdoan. 
You can use the markdown syntax to make it better :D.
Hope you enjoy writing documentation while working in future.

**Comment by nguyenminhdoan** [comment]
Thank you for your instruction @nghiaht , I'll try to make it better next time.
